version: "3.7"
services:
  mypostgres:
    image: postgres
    container_name: mypostgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "Giorgi2008!"
      POSTGRES_DB: "ticketing-app"

#when we use dash that means that we can define more then one port
    ports:
      - "5435:5432"
#it should be all the time updated.
    restart: always
# We copy-pasted from latest postgres version in DockerHub, data comes from postgres VOLUMES;
    volumes:
      - initdb:/var/lib/postgresql/data
#I defined my networks here.
    networks:
      - webnet
  ticketing-app:
    build: .
    container_name: ticketingapp
    ports:
      - "8080:8080"
    networks:
      - webnet
    depends_on:
      - mypostgres
networks:
    webnet:
      driver: bridge
#this is big title, name can be anyname
volumes:
  initdb:
